version: '3.8'

services:
  trading-bot:
    build: .
    container_name: pennystocks-finder
    volumes:
      - ./:/app/
      - ./logs:/app/logs
    environment:
      - TZ=UTC
    restart: unless-stopped